name = "MagnonRenormalization"
uuid = "bd1e1d5b-a5ec-4a3d-b4a5-f136a464cbd0"
authors = ["YaozhenghangMa <Yaozhenghang.Ma@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Brillouin = "0.5"
OMEinsum = "0.7, 0.8"
Statistics = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
